Started logging messages at Sun Jul 16 15:17:24 2017
Info:    Using UV tolerance 1e-006
Info:    Using UV tolerance 1e-006
Info:    HwNlibToTSLib options selected:
Info:        Points: Off
Info:        Curves: On
Info:        Surfaces: Off
Info:        BReps: On
Info:        Do not create IwAssembly/IwAssemblyInstance objects
Info:        Making untrimmed surfaces into BReps
Info:        Making solids into single BReps
Info:        Make components of failed trims
Info:        Make faces of failed B-reps
Info:    HW SAT v1.2.6-maint
Info:    Reading 
Info:    Processing 
Info:    Transferring 
Info:    
Info:    Found 0 points in file
Info:    Found 0 curves in file
Info:    Found 0 surfaces in file
Info:    Found 0 trimmed surfaces in file
Info:    Found 1 B-reps in file
Info:    Found 378 B-rep faces in file
Info:    
Info:    Using 3D tolerance 1e-006
Info:    Working on 0
Info:        Working on 89
Info:            Created 
Info:        Working on 90
Info:            Created 
Info:        Working on 134
Info:            Created 
Info:        Working on 135
Info:            Created 
Info:        Working on 12
Info:            Created 
Info:        Working on 126
Info:            Created 
Info:        Working on 127
Info:            Created 
Info:        Working on 177
Info:            Created 
Info:        Working on 178
Info:            Created 
Info:        Working on 17
Info:            Created 
Info:        Working on 169
Info:            Created 
Info:        Working on 170
Info:            Created 
Info:        Working on 225
Info:            Created 
Info:        Working on 224
Info:            Created 
Info:        Working on 24
Info:            Created 
Info:        Working on 35
Info:            Created 
Info:        Working on 295
Info:            Created 
Info:        Working on 296
Info:            Created 
Info:        Working on 374
Info:            Created 
Info:        Working on 375
Info:            Created 
Info:        Working on 57
Info:            Created 
Info:        Working on 368
Info:            Created 
Info:        Working on 369
Info:            Created 
Info:        Working on 463
Info:            Created 
Info:        Working on 464
Info:            Created 
Info:        Working on 96
Info:            Created 
Info:        Working on 458
Info:            Created 
Info:        Working on 580
Info:            Created 
Info:        Working on 147
Info:            Created 
Info:        Working on 578
Info:            Created 
Info:        Working on 710
Info:            Created 
Info:        Working on 203
Info:            Created 
Info:        Working on 708
Info:            Created 
Info:        Working on 843
Info:            Created 
Info:        Working on 264
Info:            Created 
Info:        Working on 841
Info:            Created 
Info:        Working on 973
Info:            Created 
Info:        Working on 341
Info:            Created 
Info:        Working on 969
Info:            Created 
Info:        Working on 970
Info:            Created 
Info:        Working on 1089
Info:            Created 
Info:        Working on 1091
Info:            Created 
Info:        Working on 439
Info:            Created 
Info:        Working on 325
Info:            Created 
Info:        Working on 789
Info:            Created 
Info:        Working on 416
Info:            Created 
Info:        Working on 1054
Info:            Created 
Info:        Working on 786
Info:            Created 
Info:        Working on 531
Info:            Created 
Info:        Working on 401
Info:            Created 
Info:        Working on 909
Info:            Created 
Info:        Working on 512
Info:            Created 
Info:        Working on 1163
Info:            Created 
Info:        Working on 603
Info:            Created 
Info:        Working on 643
Info:            Created 
Info:        Working on 733
Info:            Created 
Info:        Working on 1240
Info:            Created 
Info:        Working on 783
Info:            Created 
Info:        Working on 1383
Info:            Created 
Info:        Working on 1237
Info:            Created 
Info:        Working on 914
Info:            Created 
Info:        Working on 863
Info:            Created 
Info:        Working on 1355
Info:            Created 
Info:        Working on 995
Info:            Created 
Info:        Working on 1703
Info:            Created 
Info:        Working on 1352
Info:            Created 
Info:        Working on 1119
Info:            Created 
Info:        Working on 1698
Info:            Created 
Info:        Working on 986
Info:            Created 
Info:        Working on 1109
Info:            Created 
Info:        Working on 1903
Info:            Created 
Info:        Working on 1106
Info:            Created 
Info:        Working on 1222
Info:            Created 
Info:        Working on 2122
Info:            Created 
Info:        Working on 1219
Info:            Created 
Info:        Working on 1345
Info:            Created 
Info:        Working on 2360
Info:            Created 
Info:        Working on 1342
Info:            Created 
Info:        Working on 1496
Info:            Created 
Info:        Working on 2616
Info:            Created 
Info:        Working on 2617
Info:            Created 
Info:        Working on 2895
Info:            Created 
Info:        Working on 2899
Info:            Created 
Info:        Working on 1687
Info:            Created 
Info:        Working on 2886
Info:            Created 
Info:        Working on 2887
Info:            Created 
Info:        Working on 3187
Info:            Created 
Info:        Working on 3191
Info:            Created 
Info:        Working on 1893
Info:            Created 
Info:        Working on 3178
Info:            Created 
Info:        Working on 3179
Info:            Created 
Info:        Working on 3502
Info:            Created 
Info:        Working on 3506
Info:            Created 
Info:        Working on 2110
Info:            Created 
Info:        Working on 3493
Info:            Created 
Info:        Working on 3494
Info:            Created 
Info:        Working on 3842
Info:            Created 
Info:        Working on 3846
Info:            Created 
Info:        Working on 2342
Info:            Created 
Info:        Working on 3833
Info:            Created 
Info:        Working on 3834
Info:            Created 
Info:        Working on 4213
Info:            Created 
Info:        Working on 4217
Info:            Created 
Info:        Working on 2580
Info:            Created 
Info:        Working on 4204
Info:            Created 
Info:        Working on 4205
Info:            Created 
Info:        Working on 4613
Info:            Created 
Info:        Working on 4617
Info:            Created 
Info:        Working on 2851
Info:            Created 
Info:        Working on 4604
Info:            Created 
Info:        Working on 4605
Info:            Created 
Info:        Working on 5013
Info:            Created 
Info:        Working on 5014
Info:            Created 
Info:        Working on 3142
Info:            Created 
Info:        Working on 5009
Info:            Created 
Info:        Working on 5010
Info:            Created 
Info:        Working on 5213
Info:            Created 
Info:        Working on 5206
Info:            Created 
Info:        Working on 3458
Info:            Created 
Info:        Working on 5375
Info:            Created 
Info:        Working on 5376
Info:            Created 
Info:        Working on 5653
Info:            Created 
Info:        Working on 5657
Info:            Created 
Info:        Working on 3797
Info:            Created 
Info:        Working on 1798
Info:            Created 
Info:        Working on 1797
Info:            Created 
Info:        Working on 1418
Info:            Created 
Info:        Working on 1417
Info:            Created 
Info:        Working on 1793
Info:            Created 
Info:        Working on 1941
Info:            Created 
Info:        Working on 1942
Info:            Created 
Info:        Working on 1537
Info:            Created 
Info:        Working on 1538
Info:            Created 
Info:        Working on 1730
Info:            Created 
Info:        Working on 2418
Info:            Created 
Info:        Working on 2419
Info:            Created 
Info:        Working on 1959
Info:            Created 
Info:        Working on 1960
Info:            Created 
Info:        Working on 1946
Info:            Created 
Info:        Working on 2654
Info:            Created 
Info:        Working on 2655
Info:            Created 
Info:        Working on 2148
Info:            Created 
Info:        Working on 2149
Info:            Created 
Info:        Working on 2168
Info:            Created 
Info:        Working on 2925
Info:            Created 
Info:        Working on 2924
Info:            Created 
Info:        Working on 2378
Info:            Created 
Info:        Working on 2377
Info:            Created 
Info:        Working on 2399
Info:            Created 
Info:        Working on 3580
Info:            Created 
Info:        Working on 3579
Info:            Created 
Info:        Working on 2936
Info:            Created 
Info:        Working on 2935
Info:            Created 
Info:        Working on 2661
Info:            Created 
Info:        Working on 3745
Info:            Created 
Info:        Working on 2918
Info:            Created 
Info:        Working on 2946
Info:            Created 
Info:        Working on 4108
Info:            Created 
Info:        Working on 3238
Info:            Created 
Info:        Working on 3257
Info:            Created 
Info:        Working on 4509
Info:            Created 
Info:        Working on 3574
Info:            Created 
Info:        Working on 3586
Info:            Created 
Info:        Working on 4930
Info:            Created 
Info:        Working on 3428
Info:            Created 
Info:        Working on 3768
Info:            Created 
Info:        Working on 4502
Info:            Created 
Info:        Working on 4924
Info:            Created 
Info:        Working on 4025
Info:            Created 
Info:        Working on 4421
Info:            Created 
Info:        Working on 4143
Info:            Created 
Info:        Working on 4303
Info:            Created 
Info:        Working on 4727
Info:            Created 
Info:        Working on 5464
Info:            Created 
Info:        Working on 5123
Info:            Created 
Info:        Working on 4552
Info:            Created 
Info:        Working on 5110
Info:            Created 
Info:        Working on 4704
Info:            Created 
Info:        Working on 5450
Info:            Created 
Info:        Working on 5730
Info:            Created 
Info:        Working on 4968
Info:            Created 
Info:        Working on 5677
Info:            Created 
Info:        Working on 5909
Info:            Created 
Info:        Working on 5978
Info:            Created 
Info:        Working on 5975
Info:            Created 
Info:        Working on 5331
Info:            Created 
Info:        Working on 5775
Info:            Created 
Info:        Working on 5785
Info:            Created 
Info:        Working on 5782
Info:            Created 
Info:        Working on 5776
Info:            Created 
Info:        Working on 5621
Info:            Created 
Info:        Working on 3343
Info:            Created 
Info:        Working on 3417
Info:            Created 
Info:        Working on 3736
Info:            Created 
Info:        Working on 4100
Info:            Created 
Info:        Working on 4925
Info:            Created 
Info:        Working on 5304
Info:            Created 
Info:        Working on 5610
Info:            Created 
Info:        Working on 5541
Info:            Created 
Info:        Working on 5224
Info:            Created 
Info:        Working on 4832
Info:            Created 
Info:        Working on 4412
Info:            Created 
Info:        Working on 4013
Info:            Created 
Info:        Working on 3654
Info:            Created 
Info:        Working on 3344
Info:            Created 
Info:        Working on 5237
Info:            Created 
Info:        Working on 5238
Info:            Created 
Info:        Working on 4962
Info:            Created 
Info:        Working on 4961
Info:            Created 
Info:        Working on 5324
Info:            Created 
Info:        Working on 5616
Info:            Created 
Info:        Working on 5788
Info:            Created 
Info:        Working on 5546
Info:            Created 
Info:        Working on 2955
Info:            Created 
Info:        Working on 2956
Info:            Created 
Info:        Working on 2157
Info:            Created 
Info:        Working on 2158
Info:            Created 
Info:        Working on 2254
Info:            Created 
Info:        Working on 3025
Info:            Created 
Info:        Working on 3335
Info:            Created 
Info:        Working on 2505
Info:            Created 
Info:        Working on 3665
Info:            Created 
Info:        Working on 2787
Info:            Created 
Info:        Working on 3087
Info:            Created 
Info:        Working on 4837
Info:            Created 
Info:        Working on 3402
Info:            Created 
Info:        Working on 5226
Info:            Created 
Info:        Working on 3730
Info:            Created 
Info:        Working on 5217
Info:            Created 
Info:        Working on 4091
Info:            Created 
Info:        Working on 4823
Info:            Created 
Info:        Working on 4491
Info:            Created 
Info:        Working on 4403
Info:            Created 
Info:        Working on 4912
Info:            Created 
Info:        Working on 4004
Info:            Created 
Info:        Working on 4829
Info:            Created 
Info:        Working on 3645
Info:            Created 
Info:        Working on 4409
Info:            Created 
Info:        Working on 3319
Info:            Created 
Info:        Working on 4010
Info:            Created 
Info:        Working on 3014
Info:            Created 
Info:        Working on 3651
Info:            Created 
Info:        Working on 2744
Info:            Created 
Info:        Working on 3325
Info:            Created 
Info:        Working on 2745
Info:            Created 
Info:        Working on 3034
Info:            Created 
Info:        Working on 3340
Info:            Created 
Info:        Working on 4939
Info:            Created 
Info:        Working on 4525
Info:            Created 
Info:        Working on 3672
Info:            Created 
Info:        Working on 5312
Info:            Created 
Info:        Working on 4032
Info:            Created 
Info:        Working on 5316
Info:            Created 
Info:        Working on 4428
Info:            Created 
Info:        Working on 4951
Info:            Created 
Info:        Working on 4844
Info:            Created 
Info:        Working on 4537
Info:            Created 
Info:        Working on 5229
Info:            Created 
Info:        Working on 4138
Info:            Created 
Info:        Working on 4958
Info:            Created 
Info:        Working on 4139
Info:            Created 
Info:        Working on 4547
Info:            Created 
Info:        Working on 4943
Info:            Created 
Info:        Working on 3251
Info:            Created 
Info:        Working on 2637
Info:            Created 
Info:        Working on 2409
Info:            Created 
Info:        Working on 2410
Info:            Created 
Info:        Working on 2673
Info:            Created 
Info:        Working on 2951
Info:            Created 
Info:        Working on 2650
Info:            Created 
Info:        Working on 2414
Info:            Created 
Info:        Working on 1937
Info:            Created 
Info:        Working on 1716
Info:            Created 
Info:        Working on 1717
Info:            Created 
Info:        Working on 1933
Info:            Created 
Info:        Working on 2153
Info:            Created 
Info:        Working on 1597
Info:            Created 
Info:        Working on 1783
Info:            Created 
Info:        Working on 1784
Info:            Created 
Info:        Working on 1777
Info:            Created 
Info:        Working on 1776
Info:            Created 
Info:        Working on 1802
Info:            Created 
Info:        Working on 1999
Info:            Created 
Info:        Working on 2000
Info:            Created 
Info:        Working on 1996
Info:            Created 
Info:        Working on 1995
Info:            Created 
Info:        Working on 2019
Info:            Created 
Info:        Working on 2226
Info:            Created 
Info:        Working on 2227
Info:            Created 
Info:        Working on 2223
Info:            Created 
Info:        Working on 2222
Info:            Created 
Info:        Working on 2258
Info:            Created 
Info:        Working on 2458
Info:            Created 
Info:        Working on 2459
Info:            Created 
Info:        Working on 2455
Info:            Created 
Info:        Working on 2454
Info:            Created 
Info:        Working on 2511
Info:            Created 
Info:        Working on 2716
Info:            Created 
Info:        Working on 2717
Info:            Created 
Info:        Working on 2713
Info:            Created 
Info:        Working on 2712
Info:            Created 
Info:        Working on 2798
Info:            Created 
Info:        Working on 2996
Info:            Created 
Info:        Working on 2997
Info:            Created 
Info:        Working on 2993
Info:            Created 
Info:        Working on 2992
Info:            Created 
Info:        Working on 3102
Info:            Created 
Info:        Working on 3301
Info:            Created 
Info:        Working on 3302
Info:            Created 
Info:        Working on 3298
Info:            Created 
Info:        Working on 3297
Info:            Created 
Info:        Working on 3421
Info:            Created 
Info:        Working on 3627
Info:            Created 
Info:        Working on 3628
Info:            Created 
Info:        Working on 3624
Info:            Created 
Info:        Working on 3623
Info:            Created 
Info:        Working on 3751
Info:            Created 
Info:        Working on 3986
Info:            Created 
Info:        Working on 3987
Info:            Created 
Info:        Working on 3983
Info:            Created 
Info:        Working on 3982
Info:            Created 
Info:        Working on 4115
Info:            Created 
Info:        Working on 4384
Info:            Created 
Info:        Working on 4386
Info:            Created 
Info:        Working on 4515
Info:            Created 
Info:        Working on 4376
Info:            Created 
Info:        Working on 4375
Info:            Created 
Info:        Working on 4807
Info:            Created 
Info:        Working on 4798
Info:            Created 
Info:        Working on 4799
Info:            Created 
Info:        Working on 5210
Info:            Created 
Info:        Working on 5195
Info:            Created 
Info:        Working on 5198
Info:            Created 
Info:        Working on 5535
Info:            Created 
Info:        Working on 4794
Info:            Created 
Info:        Working on 4793
Info:            Created 
Info:        Working on 5203
Info:            Created 
Info:        Working on 5506
Info:            Created 
Info:        Working on 5508
Info:            Created 
Info:        Working on 5532
Info:            Created 
Info:        Working on 5187
Info:            Created 
Info:        Working on 5186
Info:            Created 
Info:        Working on 5518
Info:            Created 
Info:        Working on 5381
Info:            Created 
Info:        Working on 5042
Info:            Created 
Info:        Working on 5028
Info:            Created 
Info:        Working on 5498
Info:            Created 
Info:        Working on 5395
Info:            Created 
Info:        Working on 5384
Info:            Created 
Info:        Working on 5050
Info:            Created 
Info:        Working on 4657
Info:            Created 
Info:        Working on 4636
Info:            Created 
Info:        Working on 5387
Info:            Created 
Info:        Working on 5035
Info:            Created 
Info:        Working on 5034
Info:            Created 
Info:        Working on 5054
Info:            Created 
Info:        Working on 4653
Info:            Created 
Info:        Working on 4644
Info:            Created 
Info:        Working on 5684
Info:            Created 
Info:        Working on 5069
Info:            Created 
Info:        Working on 5918
Info:            Created 
Info:        Working on 5418
Info:            Created 
Info:        Working on 5059
Info:            Created 
Info:        Working on 6105
Info:            Created 
Info:        Working on 5699
Info:            Created 
Info:        Working on 6283
Info:            Created 
Info:        Working on 5933
Info:            Created 
Info:        Working on 5408
Info:            Created 
Info:        Working on 6467
Info:            Created 
Info:        Working on 6121
Info:            Created 
Info:        Working on 6529
Info:            Created 
Info:        Working on 6301
Info:            Created 
Info:        Working on 5689
Info:            Created 
Info:        Working on 6675
Info:            Created 
Info:        Working on 6487
Info:            Created 
Info:        Working on 6723
Info:            Created 
Info:        Working on 6679
Info:            Created 
Info:        Working on 5923
Info:            Created 
Info:        Working on 6872
Info:            Created 
Info:        Working on 6873
Info:            Created 
Info:        Working on 6921
Info:            Created 
Info:        Working on 6920
Info:            Created 
Info:        Working on 6110
Info:            Created 
Info:        Working on 7071
Info:            Created 
Info:        Working on 7072
Info:            Created 
Info:        Working on 7120
Info:            Created 
Info:        Working on 7119
Info:            Created 
Info:        Working on 6288
Info:            Created 
Info:        Working on 7276
Info:            Created 
Info:        Working on 7277
Info:            Created 
Info:        Working on 7325
Info:            Created 
Info:        Working on 7324
Info:            Created 
Info:        Working on 6472
Info:            Created 
Info:        Working on 7482
Info:            Created 
Info:        Working on 7483
Info:            Created 
Info:        Working on 7530
Info:            Created 
Info:        Working on 7529
Info:            Created 
Info:        Working on 6660
Info:            Created 
Info:        Working on 7687
Info:            Created 
Info:        Working on 7688
Info:            Created 
Info:        Working on 7731
Info:            Created 
Info:        Working on 7730
Info:            Created 
Info:        Working on 6854
Info:            Created 
Info:        Working on 7882
Info:            Created 
Info:        Working on 7883
Info:            Created 
Info:        Working on 7918
Info:            Created 
Info:        Working on 7917
Info:            Created 
Info:        Working on 7053
Info:            Created 
Info:        Working on 8046
Info:            Created 
Info:        Working on 8047
Info:            Created 
Info:        Working on 8069
Info:            Created 
Info:        Working on 8068
Info:            Created 
Info:        Working on 7258
Info:            Created 
Info:        Working on 8171
Info:            Created 
Info:        Working on 8036
Info:            Created 
Info:        Working on 8144
Info:            Created 
Info:        Working on 7863
Info:            Created 
Info:        Working on 7464
Info:            Created 
Info:        Working on 7995
Info:            Created 
Info:        Working on 7661
Info:            Created 
Info:        Working on 7810
Info:            Created 
Info:        Working on 7454
Info:            Created 
Info:        Working on 7669
Info:            Created 
Info:        Working on 7609
Info:            Created 
Info:        Working on 7248
Info:            Created 
Info:        Working on 7404
Info:            Created 
Info:        Working on 7043
Info:            Created 
Info:        Working on 7458
Info:            Created 
Info:        Working on 7199
Info:            Created 
Info:        Working on 6844
Info:            Created 
Info:        Working on 7000
Info:            Created 
Info:        Working on 6650
Info:            Created 
Info:        Working on 7047
Info:            Created 
Info:        Working on 6802
Info:            Created 
Info:        Working on 6458
Info:            Created 
Info:        Working on 6608
Info:            Created 
Info:        Working on 6273
Info:            Created 
Info:        Working on 6654
Info:            Created 
Info:        Working on 6418
Info:            Created 
Info:        Working on 6097
Info:            Created 
Info:        Working on 6065
Info:            Created 
Info:        Working on 5906
Info:            Created 
Info:        Working on 6277
Info:            Created 
Info:        Working on 6069
Info:            Created 
Info:        Working on 5897
Info:            Created 
Info:        Working on 6425
Info:            Created 
Info:        Working on 6085
Info:            Created 
Info:        Working on 6261
Info:            Created 
Info:        Working on 6615
Info:            Created 
Info:        Working on 6256
Info:            Created 
Info:        Working on 6809
Info:            Created 
Info:        Working on 6440
Info:            Created 
Info:        Working on 6446
Info:            Created 
Info:        Working on 7006
Info:            Created 
Info:        Working on 6632
Info:            Created 
Info:        Working on 7206
Info:            Created 
Info:        Working on 6825
Info:            Created 
Info:        Working on 6638
Info:            Created 
Info:        Working on 7408
Info:            Created 
Info:        Working on 7026
Info:            Created 
Info:        Working on 7432
Info:            Created 
Info:        Working on 7228
Info:            Created 
Info:        Working on 6832
Info:            Created 
Info:        Working on 7644
Info:            Created 
Info:        Working on 7436
Info:            Created 
Info:        Working on 7641
Info:            Created 
Info:        Working on 7640
Info:            Created 
Info:        Working on 7031
Info:            Created 
Info:        Working on 7846
Info:            Created 
Info:        Working on 7847
Info:            Created 
Info:        Working on 7843
Info:            Created 
Info:        Working on 7842
Info:            Created 
Info:        Working on 7235
Info:            Created 
Info:        Working on 8026
Info:            Created 
Info:        Working on 8027
Info:            Created 
Info:        Working on 8023
Info:            Created 
Info:        Working on 8022
Info:            Created 
Info:        Working on 7441
Info:            Created 
Info:        Working on 8164
Info:            Created 
Info:        Working on 8165
Info:            Created 
Info:        Working on 8161
Info:            Created 
Info:        Working on 8160
Info:            Created 
Info:        Working on 7650
Info:            Created 
Info:        Working on 8259
Info:            Created 
Info:        Working on 8260
Info:            Created 
Info:        Working on 8256
Info:            Created 
Info:        Working on 8178
Info:            Created 
Info:        Working on 7854
Info:            Created 
Info:        Working on 8265
Info:            Created 
Info:        Working on 8062
Info:            Created 
Info:        Working on 8175
Info:            Created 
Info:        Working on 7901
Info:            Created 
Info:        Working on 8032
Info:            Created 
Info:        Working on 8054
Info:            Created 
Info:        Working on 7707
Info:            Created 
Info:        Working on 7890
Info:            Created 
Info:        Working on 7502
Info:            Created 
Info:        Working on 7905
Info:            Created 
Info:        Working on 7695
Info:            Created 
Info:        Working on 7296
Info:            Created 
Info:        Working on 7490
Info:            Created 
Info:        Working on 7091
Info:            Created 
Info:        Working on 7506
Info:            Created 
Info:        Working on 7284
Info:            Created 
Info:        Working on 6892
Info:            Created 
Info:        Working on 7079
Info:            Created 
Info:        Working on 6698
Info:            Created 
Info:        Working on 7095
Info:            Created 
Info:        Working on 6880
Info:            Created 
Info:        Working on 6506
Info:            Created 
Info:        Working on 6686
Info:            Created 
Info:        Working on 6320
Info:            Created 
Info:        Working on 6702
Info:            Created 
Info:        Working on 6494
Info:            Created 
Info:        Working on 6142
Info:            Created 
Info:        Working on 6308
Info:            Created 
Info:        Working on 5954
Info:            Created 
Info:        Working on 6324
Info:            Created 
Info:        Working on 6130
Info:            Created 
Info:        Working on 5720
Info:            Created 
Info:        Working on 5942
Info:            Created 
Info:        Working on 5439
Info:            Created 
Info:        Working on 5958
Info:            Created 
Info:        Working on 5708
Info:            Created 
Info:        Working on 5087
Info:            Created 
Info:        Working on 5427
Info:            Created 
Info:        Working on 4680
Info:            Created 
Info:        Working on 5443
Info:            Created 
Info:        Working on 4663
Info:            Created 
Info:        Working on 4253
Info:            Created 
Info:        Working on 4237
Info:            Created 
Info:        Working on 4667
Info:            Created 
Info:        Working on 4244
Info:            Created 
Info:        Working on 4243
Info:            Created 
Info:        Working on 4261
Info:            Created 
Info:        Working on 3888
Info:            Created 
Info:        Working on 3866
Info:            Created 
Info:        Working on 5098
Info:            Created 
Info:        Working on 4284
Info:            Created 
Info:        Working on 4265
Info:            Created 
Info:        Working on 4268
Info:            Created 
Info:        Working on 3883
Info:            Created 
Info:        Working on 3874
Info:            Created 
Info:        Working on 5731
Info:            Created 
Info:        Working on 5127
Info:            Created 
Info:        Working on 4273
Info:            Created 
Info:        Working on 5960
Info:            Created 
Info:        Working on 5456
Info:            Created 
Info:        Working on 4693
Info:            Created 
Info:        Working on 3894
Info:            Created 
Info:        Working on 3543
Info:            Created 
Info:        Working on 3527
Info:            Created 
Info:        Working on 4718
Info:            Created 
Info:        Working on 3913
Info:            Created 
Info:        Working on 3898
Info:            Created 
Info:        Working on 3551
Info:            Created 
Info:        Working on 3232
Info:            Created 
Info:        Working on 3210
Info:            Created 
Info:        Working on 3901
Info:            Created 
Info:        Working on 3534
Info:            Created 
Info:        Working on 3533
Info:            Created 
Info:        Working on 3555
Info:            Created 
Info:        Working on 3227
Info:            Created 
Info:        Working on 3218
Info:            Created 
Info:        Working on 4314
Info:            Created 
Info:        Working on 3571
Info:            Created 
Info:        Working on 4737
Info:            Created 
Info:        Working on 3937
Info:            Created 
Info:        Working on 3560
Info:            Created 
Info:        Working on 5136
Info:            Created 
Info:        Working on 4329
Info:            Created 
Info:        Working on 5470
Info:            Created 
Info:        Working on 4754
Info:            Created 
Info:        Working on 3926
Info:            Created 
Info:        Working on 5741
Info:            Created 
Info:        Working on 5151
Info:            Created 
Info:        Working on 5963
Info:            Created 
Info:        Working on 5485
Info:            Created 
Info:        Working on 4319
Info:            Created 
Info:        Working on 5964
Info:            Created 
Info:        Working on 5752
Info:            Created 
Info:        Working on 5792
Info:            Created 
Info:        Working on 5967
Info:            Created 
Info:        Working on 4742
Info:            Created 
Info:        Working on 5555
Info:            Created 
Info:        Working on 5987
Info:            Created 
Info:        Working on 5250
Info:            Created 
Info:        Working on 5799
Info:            Created 
Info:        Working on 5140
Info:            Created 
Info:        Working on 4867
Info:            Created 
Info:        Working on 5565
Info:            Created 
Info:        Working on 4445
Info:            Created 
Info:        Working on 5260
Info:            Created 
Info:        Working on 5257
Info:            Created 
Info:        Working on 4046
Info:            Created 
Info:        Working on 4877
Info:            Created 
Info:        Working on 3685
Info:            Created 
Info:        Working on 4455
Info:            Created 
Info:        Working on 4452
Info:            Created 
Info:        Working on 3358
Info:            Created 
Info:        Working on 4056
Info:            Created 
Info:        Working on 3047
Info:            Created 
Info:        Working on 3695
Info:            Created 
Info:        Working on 3692
Info:            Created 
Info:        Working on 2758
Info:            Created 
Info:        Working on 3368
Info:            Created 
Info:        Working on 2499
Info:            Created 
Info:        Working on 3078
Info:            Created 
Info:        Working on 3054
Info:            Created 
Info:        Working on 2500
Info:            Created 
Info:        Working on 3077
Info:            Created 
Info:        Working on 2771
Info:            Created 
Info:        Working on 3389
Info:            Created 
Info:        Working on 3074
Info:            Created 
Info:        Working on 3066
Info:            Created 
Info:        Working on 3716
Info:            Created 
Info:        Working on 3381
Info:            Created 
Info:        Working on 4076
Info:            Created 
Info:        Working on 3393
Info:            Created 
Info:        Working on 3708
Info:            Created 
Info:        Working on 4475
Info:            Created 
Info:        Working on 4068
Info:            Created 
Info:        Working on 4896
Info:            Created 
Info:        Working on 3720
Info:            Created 
Info:        Working on 4467
Info:            Created 
Info:        Working on 5278
Info:            Created 
Info:        Working on 4888
Info:            Created 
Info:        Working on 5580
Info:            Created 
Info:        Working on 4081
Info:            Created 
Info:        Working on 5270
Info:            Created 
Info:        Working on 5807
Info:            Created 
Info:        Working on 5574
Info:            Created 
Info:        Working on 5842
Info:            Created 
Info:        Working on 4480
Info:            Created 
Info:        Working on 5806
Info:            Created 
Info:        Working on 6011
Info:            Created 
Info:        Working on 5993
Info:            Created 
Info:        Working on 6031
Info:            Created 
Info:        Working on 4901
Info:            Created 
Info:        Working on 6160
Info:            Created 
Info:        Working on 6180
Info:            Created 
Info:        Working on 6204
Info:            Created 
Info:        Working on 6203
Info:            Created 
Info:        Working on 5283
Info:            Created 
Info:        Working on 6362
Info:            Created 
Info:        Working on 6363
Info:            Created 
Info:        Working on 6387
Info:            Created 
Info:        Working on 6386
Info:            Created 
Info:        Working on 5585
Info:            Created 
Info:        Working on 6552
Info:            Created 
Info:        Working on 6553
Info:            Created 
Info:        Working on 6577
Info:            Created 
Info:        Working on 6576
Info:            Created 
Info:        Working on 5812
Info:            Created 
Info:        Working on 6746
Info:            Created 
Info:        Working on 6747
Info:            Created 
Info:        Working on 6771
Info:            Created 
Info:        Working on 6770
Info:            Created 
Info:        Working on 5998
Info:            Created 
Info:        Working on 6944
Info:            Created 
Info:        Working on 6945
Info:            Created 
Info:        Working on 6969
Info:            Created 
Info:        Working on 6968
Info:            Created 
Info:        Working on 6165
Info:            Created 
Info:        Working on 7143
Info:            Created 
Info:        Working on 7144
Info:            Created 
Info:        Working on 7168
Info:            Created 
Info:        Working on 7167
Info:            Created 
Info:        Working on 6344
Info:            Created 
Info:        Working on 7348
Info:            Created 
Info:        Working on 7349
Info:            Created 
Info:        Working on 7373
Info:            Created 
Info:        Working on 7372
Info:            Created 
Info:        Working on 6534
Info:            Created 
Info:        Working on 7553
Info:            Created 
Info:        Working on 7554
Info:            Created 
Info:        Working on 7578
Info:            Created 
Info:        Working on 7577
Info:            Created 
Info:        Working on 6728
Info:            Created 
Info:        Working on 7754
Info:            Created 
Info:        Working on 7755
Info:            Created 
Info:        Working on 7779
Info:            Created 
Info:        Working on 7778
Info:            Created 
Info:        Working on 6926
Info:            Created 
Info:        Working on 7941
Info:            Created 
Info:        Working on 7942
Info:            Created 
Info:        Working on 7966
Info:            Created 
Info:        Working on 7965
Info:            Created 
Info:        Working on 7125
Info:            Created 
Info:        Working on 8092
Info:            Created 
Info:        Working on 8093
Info:            Created 
Info:        Working on 8117
Info:            Created 
Info:        Working on 8116
Info:            Created 
Info:        Working on 7330
Info:            Created 
Info:        Working on 8203
Info:            Created 
Info:        Working on 8204
Info:            Created 
Info:        Working on 8228
Info:            Created 
Info:        Working on 8227
Info:            Created 
Info:        Working on 7535
Info:            Created 
Info:        Working on 8288
Info:            Created 
Info:        Working on 8289
Info:            Created 
Info:        Working on 8313
Info:            Created 
Info:        Working on 8312
Info:            Created 
Info:        Working on 7736
Info:            Created 
Info:        Working on 8362
Info:            Created 
Info:        Working on 8363
Info:            Created 
Info:        Working on 8387
Info:            Created 
Info:        Working on 8386
Info:            Created 
Info:        Working on 7923
Info:            Created 
Info:        Working on 8434
Info:            Created 
Info:        Working on 8435
Info:            Created 
Info:        Working on 8459
Info:            Created 
Info:        Working on 8458
Info:            Created 
Info:        Working on 8074
Info:            Created 
Info:        Working on 8503
Info:            Created 
Info:        Working on 8504
Info:            Created 
Info:        Working on 8526
Info:            Created 
Info:        Working on 8525
Info:            Created 
Info:        Working on 8185
Info:            Created 
Info:        Working on 8562
Info:            Created 
Info:        Working on 8563
Info:            Created 
Info:        Working on 8580
Info:            Created 
Info:        Working on 8579
Info:            Created 
Info:        Working on 8270
Info:            Created 
Info:        Working on 8602
Info:            Created 
Info:        Working on 8603
Info:            Created 
Info:        Working on 8614
Info:            Created 
Info:        Working on 8613
Info:            Created 
Info:        Working on 8344
Info:            Created 
Info:        Working on 8621
Info:            Created 
Info:        Working on 8615
Info:            Created 
Info:        Working on 8624
Info:            Created 
Info:        Working on 8584
Info:            Created 
Info:        Working on 8416
Info:            Created 
Info:        Working on 8618
Info:            Created 
Info:        Working on 8536
Info:            Created 
Info:        Working on 8592
Info:            Created 
Info:        Working on 8471
Info:            Created 
Info:        Working on 8485
Info:            Created 
Info:        Working on 8544
Info:            Created 
Info:        Working on 8400
Info:            Created 
Info:        Working on 8481
Info:            Created 
Info:        Working on 8326
Info:            Created 
Info:        Working on 8478
Info:            Created 
Info:        Working on 8410
Info:            Created 
Info:        Working on 8241
Info:            Created 
Info:        Working on 8336
Info:            Created 
Info:        Working on 8130
Info:            Created 
Info:        Working on 8333
Info:            Created 
Info:        Working on 8251
Info:            Created 
Info:        Working on 7979
Info:            Created 
Info:        Working on 8140
Info:            Created 
Info:        Working on 7792
Info:            Created 
Info:        Working on 8137
Info:            Created 
Info:        Working on 7989
Info:            Created 
Info:        Working on 7591
Info:            Created 
Info:        Working on 7802
Info:            Created 
Info:        Working on 7386
Info:            Created 
Info:        Working on 7799
Info:            Created 
Info:        Working on 7601
Info:            Created 
Info:        Working on 7181
Info:            Created 
Info:        Working on 7396
Info:            Created 
Info:        Working on 6982
Info:            Created 
Info:        Working on 7393
Info:            Created 
Info:        Working on 7191
Info:            Created 
Info:        Working on 6784
Info:            Created 
Info:        Working on 6992
Info:            Created 
Info:        Working on 6590
Info:            Created 
Info:        Working on 6989
Info:            Created 
Info:        Working on 6794
Info:            Created 
Info:        Working on 6400
Info:            Created 
Info:        Working on 6600
Info:            Created 
Info:        Working on 6217
Info:            Created 
Info:        Working on 6597
Info:            Created 
Info:        Working on 6410
Info:            Created 
Info:        Working on 6045
Info:            Created 
Info:        Working on 6227
Info:            Created 
Info:        Working on 5859
Info:            Created 
Info:        Working on 6224
Info:            Created 
Info:        Working on 6055
Info:            Created 
Info:        Working on 5634
Info:            Created 
Info:        Working on 5869
Info:            Created 
Info:        Working on 5344
Info:            Created 
Info:        Working on 5866
Info:            Created 
Info:        Working on 5644
Info:            Created 
Info:        Working on 4981
Info:            Created 
Info:        Working on 5354
Info:            Created 
Info:        Working on 4565
Info:            Created 
Info:        Working on 5351
Info:            Created 
Info:        Working on 4991
Info:            Created 
Info:        Working on 4156
Info:            Created 
Info:        Working on 4575
Info:            Created 
Info:        Working on 3781
Info:            Created 
Info:        Working on 4572
Info:            Created 
Info:        Working on 4166
Info:            Created 
Info:        Working on 3441
Info:            Created 
Info:        Working on 3791
Info:            Created 
Info:        Working on 3125
Info:            Created 
Info:        Working on 3788
Info:            Created 
Info:        Working on 3451
Info:            Created 
Info:        Working on 2832
Info:            Created 
Info:        Working on 3135
Info:            Created 
Info:        Working on 2560
Info:            Created 
Info:        Working on 3132
Info:            Created 
Info:        Working on 2842
Info:            Created 
Info:        Working on 2321
Info:            Created 
Info:        Working on 2570
Info:            Created 
Info:        Working on 2082
Info:            Created 
Info:        Working on 2567
Info:            Created 
Info:        Working on 2331
Info:            Created 
Info:        Working on 1856
Info:            Created 
Info:        Working on 2092
Info:            Created 
Info:        Working on 1640
Info:            Created 
Info:        Working on 2089
Info:            Created 
Info:        Working on 2010
Info:            Created 
Info:        Working on 1627
Info:            Created 
Info:        Working on 1583
Info:            Created 
Info:        Working on 1582
Info:            Created 
Info:        Working on 1789
Info:            Created 
Info:        Working on 1866
Info:            Created 
Info:        Working on 1452
Info:            Created 
Info:        Working on 1867
Info:            Created 
Info:        Working on 1451
Info:            Created 
Info:        Working on 1651
Info:            Created 
Info:        Working on 1871
Info:            Created 
Info:        Working on 3108
Info:            Created 
Info:        Working on 3103
Info:            Created 
Info:        Working on 2532
Info:            Created 
Info:        Working on 2517
Info:            Created 
Info:        Working on 2098
Info:            Created 
Info:        Working on 2540
Info:            Created 
Info:        Working on 2815
Info:            Created 
Info:        Working on 2044
Info:            Created 
Info:        Working on 2285
Info:            Created 
Info:        Working on 2335
Info:            Created 
Info:        Working on 2804
Info:            Created 
Info:        Working on 2528
Info:            Created 
Info:        Working on 2269
Info:            Created 
Info:        Working on 2032
Info:            Created 
Info:        Working on 2525
Info:            Created 
Info:        Working on 2297
Info:            Created 
Info:        Working on 2296
Info:            Created 
Info:        Working on 2808
Info:            Created 
Info:        Working on 1826
Info:            Created 
Info:        Working on 1825
Info:            Created 
Info:        Working on 2055
Info:            Created 
Info:        Working on 2301
Info:            Created 
Info:        Working on 2363
Info:            Created 
Info:        Working on 2125
Info:            Created 
Info:        Working on 1906
Info:            Created 
Info:        Working on 1912
Info:            Created 
Info:        Working on 1508
Info:            Created 
Info:        Working on 1541
Info:            Created 
Info:        Working on 1361
Info:            Created 
Info:        Working on 1265
Info:            Created 
Info:        Working on 1038
Info:            Created 
Info:        Working on 1156
Info:            Created 
Info:        Working on 920
Info:            Created 
Info:        Working on 1051
Info:            Created 
Info:        Working on 1168
Info:            Created 
Info:        Working on 1270
Info:            Created 
Info:        Working on 1390
Info:            Created 
Info:        Working on 1549
Info:            Created 
Info:        Working on 1746
Info:            Created 
Info:        Working on 1965
Info:            Created 
Info:        Working on 2192
Info:            Created 
Info:        Working on 2424
Info:            Created 
Info:        Working on 2682
Info:            Created 
Info:        Working on 2962
Info:            Created 
Info:        Working on 3267
Info:            Created 
Info:        Working on 3593
Info:            Created 
Info:        Working on 3952
Info:            Created 
Info:        Working on 4342
Info:            Created 
Info:        Working on 4764
Info:            Created 
Info:        Working on 5163
Info:            Created 
Info:        Working on 5494
Info:            Created 
Info:        Working on 5760
Info:            Created 
Info:        Working on 5972
Info:            Created 
Info:        Working on 6152
Info:            Created 
Info:        Working on 6330
Info:            Created 
Info:        Working on 6516
Info:            Created 
Info:        Working on 6708
Info:            Created 
Info:        Working on 6902
Info:            Created 
Info:        Working on 7101
Info:            Created 
Info:        Working on 7306
Info:            Created 
Info:        Working on 7511
Info:            Created 
Info:        Working on 7665
Info:            Created 
Info:        Working on 7252
Info:            Created 
Info:        Working on 6848
Info:            Created 
Info:        Working on 6462
Info:            Created 
Info:        Working on 5880
Info:            Created 
Info:        Working on 5888
Info:            Created 
Info:        Working on 6074
Info:            Created 
Info:        Working on 6245
Info:            Created 
Info:        Working on 6430
Info:            Created 
Info:        Working on 6620
Info:            Created 
Info:        Working on 6814
Info:            Created 
Info:        Working on 7011
Info:            Created 
Info:        Working on 7211
Info:            Created 
Info:        Working on 7413
Info:            Created 
Info:        Working on 7615
Info:            Created 
Info:        Working on 7815
Info:            Created 
Info:        Working on 7711
Info:            Created 
Info:        Working on 7300
Info:            Created 
Info:        Working on 6896
Info:            Created 
Info:        Working on 6510
Info:            Created 
Info:        Working on 6146
Info:            Created 
Info:        Working on 5724
Info:            Created 
Info:        Working on 5091
Info:            Created 
Info:        Working on 4711
Info:            Created 
Info:        Working on 4709
Info:            Created 
Info:        Working on 5116
Info:            Created 
Info:        Working on 4307
Info:            Created 
Info:        Working on 3944
Info:            Created 
Info:        Working on 3942
Info:            Created 
Info:        Working on 4335
Info:            Created 
Info:        Working on 4760
Info:            Created 
Info:        Working on 5158
Info:            Created 
Info:        Working on 5489
Info:            Created 
Info:        Working on 5562
Info:            Created 
Info:        Working on 4874
Info:            Created 
Info:        Working on 4053
Info:            Created 
Info:        Working on 3365
Info:            Created 
Info:        Working on 2782
Info:            Created 
Info:        Working on 3082
Info:            Created 
Info:        Working on 3397
Info:            Created 
Info:        Working on 3725
Info:            Created 
Info:        Working on 4086
Info:            Created 
Info:        Working on 4485
Info:            Created 
Info:        Working on 4907
Info:            Created 
Info:        Working on 5290
Info:            Created 
Info:        Working on 5595
Info:            Created 
Info:        Working on 5829
Info:            Created 
Info:        Working on 6016
Info:            Created 
Info:        Working on 6185
Info:            Created 
Info:        Working on 6368
Info:            Created 
Info:        Working on 6558
Info:            Created 
Info:        Working on 6752
Info:            Created 
Info:        Working on 6950
Info:            Created 
Info:        Working on 7149
Info:            Created 
Info:        Working on 7354
Info:            Created 
Info:        Working on 7559
Info:            Created 
Info:        Working on 7760
Info:            Created 
Info:        Working on 7947
Info:            Created 
Info:        Working on 8098
Info:            Created 
Info:        Working on 8209
Info:            Created 
Info:        Working on 8294
Info:            Created 
Info:        Working on 8368
Info:            Created 
Info:        Working on 8440
Info:            Created 
Info:        Working on 8507
Info:            Created 
Info:        Working on 8407
Info:            Created 
Info:        Working on 8248
Info:            Created 
Info:        Working on 7986
Info:            Created 
Info:        Working on 7598
Info:            Created 
Info:        Working on 7188
Info:            Created 
Info:        Working on 6791
Info:            Created 
Info:        Working on 6407
Info:            Created 
Info:        Working on 6052
Info:            Created 
Info:        Working on 5641
Info:            Created 
Info:        Working on 4988
Info:            Created 
Info:        Working on 4163
Info:            Created 
Info:        Working on 3448
Info:            Created 
Info:        Working on 2839
Info:            Created 
Info:        Working on 2328
Info:            Created 
Info:        Working on 1863
Info:            Created 
Info:        Working on 1843
Info:            Created 
Info:        Working on 2069
Info:            Created 
Info:        Working on 2307
Info:            Created 
Info:        Working on 2292
Info:            Created 
Info:        Working on 2276
Info:            Created 
Info:        Working on 689
Info:            Created 
Info:        Working on 688
Info:            Created 
Info:        Working on 905
Info:            Created 
Info:        Working on 904
Info:            Created 
Info:        Working on 1033
Info:            Created 
Info:        Working on 1151
Info:            Created 
Info:        Working on 1252
Info:            Created 
Info:        Working on 1368
Info:            Created 
Info:        Working on 1517
Info:            Created 
Info:        Working on 1328
Info:            Created 
Info:        Working on 1181
Info:            Created 
Info:        Working on 1072
Info:            Created 
Info:        Working on 946
Info:            Created 
Info:        Working on 816
Info:            Created 
Info:        Working on 950
Info:            Created 
Info:        Working on 1473
Info:            Created 
Info:        Working on 1621
Info:            Created 
Info:        Working on 1831
Info:            Created 
Info:        Working on 1886
Info:            Created 
Info:        Working on 2104
Info:            Created 
Info:        Working on 2304
Info:            Created 
Info:        Working on 2062
Info:            Created 
Info:        Working on 1837
Info:            Created 
Info:        Working on 1076
Info:            Created 
Info:        Working on 976
Info:            Created 
Info:        Working on 846
Info:            Created 
Info:        Working on 713
Info:            Created 
Info:        Working on 584
Info:            Created 
Info:        Working on 1132
Info:            Created 
Info:        Working on 1131
Info:            Created 
Info:        Working on 719
Info:            Created 
Info:        Working on 470
Info:            Created 
Info:        Working on 881
Info:            Created 
Info:        Working on 880
Info:            Created 
Info:        Working on 596
Info:            Created 
Info:        Working on 380
Info:            Created 
Info:        Working on 299
Info:            Created 
Info:        Working on 184
Info:            Created 
Info:        Working on 650
Info:            Created 
Info:        Working on 651
Info:            Created 
Info:        Working on 246
Info:            Created 
Info:        Working on 141
Info:            Created 
Info:        Working on 557
Info:            Created 
Info:        Working on 558
Info:            Created 
Info:        Working on 197
Info:            Created 
Info:        Working on 681
Info:            Created 
Info:        Working on 257
Info:            Created 
Info:        Working on 813
Info:            Created 
Info:        Working on 330
Info:            Created 
Info:        Working on 943
Info:            Created 
Info:        Working on 421
Info:            Created 
Info:        Working on 1069
Info:            Created 
Info:        Working on 536
Info:            Created 
Info:        Working on 665
Info:            Created 
Info:        Working on 1208
Info:            Created 
Info:        Working on 797
Info:            Created 
Info:        Working on 1244
Info:            Created 
Info:        Working on 929
Info:            Created 
Info:        Working on 1141
Info:            Created 
Info:        Working on 1059
Info:            Created 
Info:        Working on 1023
Info:            Created 
Info:        Working on 1175
Info:            Created 
Info:        Working on 894
Info:            Created 
Info:        Working on 1148
Info:            Created 
Info:        Working on 764
Info:            Created 
Info:        Working on 1030
Info:            Created 
Info:        Working on 633
Info:            Created 
Info:        Working on 901
Info:            Created 
Info:        Working on 634
Info:            Created 
Info:        Working on 774
Info:            Created 
Info:        Working on 822
Info:            Created 
Info:        Working on 1472
Info:            Created 
Info:        Working on 1665
Info:            Created 
Info:        Working on 955
Info:            Created 
Info:        Working on 1666
Info:            Created 
Info:        Working on 1082
Info:            Created 
Info:        Working on 2103
Info:            Created 
Info:        Working on 1193
Info:            Created 
Info:        Working on 1882
Info:            Created 
Info:        Working on 1310
Info:            Created 
Info:        Working on 1675
Info:            Created 
Info:        Working on 1457
Info:            Created 
Info:        Working on 1491
Info:            Created 
Info:        Working on 1654
Info:            Created 
Info:        Working on 1492
Info:            Created 
Info:        Working on 1682
Info:            Created 
Info:        Working on 1668
Info:            Created 
Info:        Working on 877
Info:            Created 
Info:        Working on 876
Info:            Created 
Info:        Working on 1011
Info:            Created 
Info:        Working on 1128
Info:            Created 
Info:        Working on 590
Info:            Created 
Info:        Working on 616
Info:            Created 
Info:        Working on 615
Info:            Created 
Info:        Working on 723
Info:            Created 
Info:        Working on 859
Info:            Created 
Info:        Working on 475
Info:            Created 
Info:        Working on 240
Info:            Created 
Info:        Working on 525
Info:            Created 
Info:        Working on 524
Info:            Created 
Info:        Working on 311
Info:            Created 
Info:        Working on 396
Info:            Created 
Info:        Working on 190
Info:            Created 
Info:        Working on 234
Info:            Created 
Info:        Created 
Info:    Working on BRep 0
Info:        Using 3D tolerance 1.9369e-006
Info:        Using 3D tolerance 1e-006
Info:        Created BRep 
Info:    Finished with 
Info:    Points:                 0 found       0 created       0 failed
Info:    Coordinate Systems      0 found       0 created       0 failed
Info:    Curves:                 0 found       0 created       0 failed
Info:    Surfaces:               0 found       0 created       0 failed
Info:    Trimmed Surfaces:       0 found       0 created       0 failed
Info:    Breps:                  1 found       1 created       0 failed
Finished logging messages at Sun Jul 16 15:17:25 2017
